name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build/release Electron app
        # You may pin to the exact commit or the version.
        # uses: paneron/action-electron-builder@14b133702d1b2e9749912051c43ed62b4afe56c8
        uses: paneron/action-electron-builder@v1.8.1
        with:
          # Package manager to use (`pnpm | yarn | npm`)
          package_manager: yarn # optional, default is yarn
          # GitHub authentication token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Whether the app should be released after a successful build
          release: true
          # Directory where NPM/Yarn commands should be run
          # package_root: # optional, default is .
          # Name of the optional NPM build script which is executed before `electron-builder`
          # build_script_name: # optional, default is build
          # Whether the action should execute the NPM build script before running `electron-builder`
          # skip_build: # optional
          # Whether to run `electron-builder` using the Vue CLI plugin instead of calling the command directly
          # use_vue_cli: # optional
          # Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
          # args: # optional, default is 
          # Maximum number of attempts for completing the build and release step
          # max_attempts: # optional, default is 1
          # Directory where `electron-builder` commands should be run
          # app_root: # optional
